# Generated by Django 3.1.3 on 2020-12-08 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0002_auto_20201203_0425'),
        ('usuario', '0006_auto_20201207_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorio.laboratorio'),
        ),
        migrations.AlterField(
            model_name='exames',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
